"""Public package exports for Litestar Security."""

from litestar_security.__metadata__ import __project__, __version__
from litestar_security.authentication import (
    Authenticated,
    AuthenticationMechanism,
    AuthenticationOutcome,
    AuthenticationPolicy,
    AuthenticationRegistry,
    CredentialExtraction,
    CredentialSlot,
    IdentityResolution,
    IdentityResolver,
    InvalidCredentials,
    MechanismRequirement,
    NoCredentials,
    PresentedCredential,
    RequestAuthenticator,
    VerificationUnavailable,
    all_of,
    any_of,
    at_least,
    mechanism,
    optional,
    public,
    required,
    security,
)
from litestar_security.config import ExternalCSRF, MFAConfig, PasskeyConfig, SecurityConfig
from litestar_security.context import (
    AuthenticationEvidence,
    AuthorizationSnapshot,
    CredentialRestrictions,
    LitestarSessionHandle,
    NullSessionHandle,
    Principal,
    SecurityContext,
    SessionHandle,
    SessionPersistenceUnavailableError,
    SessionUnavailableError,
)
from litestar_security.guards import (
    AssuranceRequirement,
    AssuranceTrait,
    AuthorizationDecision,
    AuthorizationPredicate,
    requires_assurance,
    requires_authenticated,
    requires_capability,
    requires_role,
    requires_scope,
    requires_team_role,
    requires_tenant,
)
from litestar_security.guards import all_of as guard_all_of
from litestar_security.guards import any_of as guard_any_of
from litestar_security.guards import at_least as guard_at_least
from litestar_security.guards import one_of as guard_one_of
from litestar_security.plugin import CurrentUser, PrincipalDependency, SecurityContextDependency, SecurityPlugin

__all__ = (
    "AssuranceRequirement",
    "AssuranceTrait",
    "Authenticated",
    "AuthenticationEvidence",
    "AuthenticationMechanism",
    "AuthenticationOutcome",
    "AuthenticationPolicy",
    "AuthenticationRegistry",
    "AuthorizationDecision",
    "AuthorizationPredicate",
    "AuthorizationSnapshot",
    "CredentialExtraction",
    "CredentialRestrictions",
    "CredentialSlot",
    "CurrentUser",
    "ExternalCSRF",
    "IdentityResolution",
    "IdentityResolver",
    "InvalidCredentials",
    "LitestarSessionHandle",
    "MFAConfig",
    "MechanismRequirement",
    "NoCredentials",
    "NullSessionHandle",
    "PasskeyConfig",
    "PresentedCredential",
    "Principal",
    "PrincipalDependency",
    "RequestAuthenticator",
    "SecurityConfig",
    "SecurityContext",
    "SecurityContextDependency",
    "SecurityPlugin",
    "SessionHandle",
    "SessionPersistenceUnavailableError",
    "SessionUnavailableError",
    "VerificationUnavailable",
    "__project__",
    "__version__",
    "all_of",
    "any_of",
    "at_least",
    "guard_all_of",
    "guard_any_of",
    "guard_at_least",
    "guard_one_of",
    "mechanism",
    "optional",
    "public",
    "required",
    "requires_assurance",
    "requires_authenticated",
    "requires_capability",
    "requires_role",
    "requires_scope",
    "requires_team_role",
    "requires_tenant",
    "security",
)
