"""Public package exports for Litestar Security."""

from typing import TYPE_CHECKING, Any

from litestar_security.__metadata__ import __project__, __version__
from litestar_security._docs import ROUTE_TAGS, RouteDocs
from litestar_security._lazy import import_optional_attribute
from litestar_security.authentication import (
    CSRF_REQUIRED_OPT_KEY,
    Authenticated,
    AuthenticationMechanism,
    AuthenticationOutcome,
    AuthenticationPolicy,
    AuthenticationRegistry,
    AuthorizationResolver,
    CredentialExtraction,
    CredentialSlot,
    CredentialVerifier,
    IdentityResolution,
    IdentityResolver,
    InvalidCredentials,
    MechanismRequirement,
    NoCredentials,
    PresentedCredential,
    VerificationUnavailable,
    all_of,
    any_of,
    at_least,
    exclude,
    mechanism,
    optional,
    public,
    required,
)
from litestar_security.config import (
    BlockingIntegration,
    ExternalCSRF,
    MFAConfig,
    PasskeyConfig,
    RaisedErrorSchema,
    SecurityConfig,
)
from litestar_security.context import (
    AuthenticationEvidence,
    AuthorizationSnapshot,
    CredentialRestrictions,
    LitestarSessionHandle,
    NullSessionHandle,
    Principal,
    ResourcePermission,
    SecurityContext,
    SessionHandle,
    SessionPersistenceUnavailableError,
    SessionUnavailableError,
    resolve_authorization,
)
from litestar_security.controllers import PublicController, SecureController
from litestar_security.guards import (
    AssuranceRequirement,
    AssuranceTrait,
    AuthorizationDecision,
    AuthorizationPredicate,
    require_all_of,
    require_any_of,
    require_assurance,
    require_at_least,
    require_authenticated,
    require_capability,
    require_one_of,
    require_role,
    require_scope,
    require_team_role,
    require_tenant,
)
from litestar_security.headers import ContentSecurityPolicy, CSPMode, SecurityHeadersConfig, csp_nonce
from litestar_security.plugin import CurrentUser, SecurityPlugin
from litestar_security.schema import ProblemDetail, RouteError, WireStruct
from litestar_security.websocket import (
    AuthorizationSnapshotRefresher,
    InMemoryWebSocketConnectTokenStore,
    IssuedWebSocketConnectToken,
    WebSocketBinding,
    WebSocketCloseCodes,
    WebSocketConnectAuthorization,
    WebSocketConnectTokenIssuer,
    WebSocketConnectTokenService,
    WebSocketConnectTokenStore,
    WebSocketRevocationSource,
    WebSocketSecurityConfig,
    issue_websocket_connect_token,
    websocket_policy_fingerprint,
)

if TYPE_CHECKING:
    from litestar_security.providers.oauth import (
        AESGCMOAuthTransactionProtector,
        GitHubOAuthProvider,
        OAuthAccountService,
        OAuthAccountStore,
        OAuthCallbackOutcome,
        OAuthConfig,
        OAuthLifecycle,
        OAuthLoginOutcome,
        OAuthProvider,
        OAuthTransactionProtectorKey,
    )

__all__ = (
    "CSRF_REQUIRED_OPT_KEY",
    "ROUTE_TAGS",
    "AESGCMOAuthTransactionProtector",
    "AssuranceRequirement",
    "AssuranceTrait",
    "Authenticated",
    "AuthenticationEvidence",
    "AuthenticationMechanism",
    "AuthenticationOutcome",
    "AuthenticationPolicy",
    "AuthenticationRegistry",
    "AuthorizationDecision",
    "AuthorizationPredicate",
    "AuthorizationResolver",
    "AuthorizationSnapshot",
    "AuthorizationSnapshotRefresher",
    "BlockingIntegration",
    "CSPMode",
    "ContentSecurityPolicy",
    "CredentialExtraction",
    "CredentialRestrictions",
    "CredentialSlot",
    "CredentialVerifier",
    "CurrentUser",
    "ExternalCSRF",
    "GitHubOAuthProvider",
    "IdentityResolution",
    "IdentityResolver",
    "InMemoryWebSocketConnectTokenStore",
    "InvalidCredentials",
    "IssuedWebSocketConnectToken",
    "LitestarSessionHandle",
    "MFAConfig",
    "MechanismRequirement",
    "NoCredentials",
    "NullSessionHandle",
    "OAuthAccountService",
    "OAuthAccountStore",
    "OAuthCallbackOutcome",
    "OAuthConfig",
    "OAuthLifecycle",
    "OAuthLoginOutcome",
    "OAuthProvider",
    "OAuthTransactionProtectorKey",
    "PasskeyConfig",
    "PresentedCredential",
    "Principal",
    "ProblemDetail",
    "PublicController",
    "RaisedErrorSchema",
    "ResourcePermission",
    "RouteDocs",
    "RouteError",
    "SecureController",
    "SecurityConfig",
    "SecurityContext",
    "SecurityHeadersConfig",
    "SecurityPlugin",
    "SessionHandle",
    "SessionPersistenceUnavailableError",
    "SessionUnavailableError",
    "VerificationUnavailable",
    "WebSocketBinding",
    "WebSocketCloseCodes",
    "WebSocketConnectAuthorization",
    "WebSocketConnectTokenIssuer",
    "WebSocketConnectTokenService",
    "WebSocketConnectTokenStore",
    "WebSocketRevocationSource",
    "WebSocketSecurityConfig",
    "WireStruct",
    "__project__",
    "__version__",
    "all_of",
    "any_of",
    "at_least",
    "csp_nonce",
    "exclude",
    "issue_websocket_connect_token",
    "mechanism",
    "optional",
    "public",
    "require_all_of",
    "require_any_of",
    "require_assurance",
    "require_at_least",
    "require_authenticated",
    "require_capability",
    "require_one_of",
    "require_role",
    "require_scope",
    "require_team_role",
    "require_tenant",
    "required",
    "resolve_authorization",
    "websocket_policy_fingerprint",
)

_OAUTH_EXPORTS = frozenset({
    "AESGCMOAuthTransactionProtector",
    "GitHubOAuthProvider",
    "OAuthAccountService",
    "OAuthAccountStore",
    "OAuthCallbackOutcome",
    "OAuthConfig",
    "OAuthLoginOutcome",
    "OAuthProvider",
    "OAuthLifecycle",
    "OAuthTransactionProtectorKey",
})


def __getattr__(name: str) -> Any:  # noqa: ANN401 - module lazy-export hooks are dynamically typed
    """Resolve curated OAuth exports without loading providers at root import."""
    if name in _OAUTH_EXPORTS:
        return import_optional_attribute("litestar_security.providers", name, extras="oauth", dependencies=frozenset())
    message = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(message)
