"""OAuth authorization transaction and provider lifecycle contracts."""

from typing import TYPE_CHECKING, Any

from litestar_security.providers.oauth._accounts import (
    AccountLinkError,
    LinkedProviderAccount,
    MemoryOAuthAccountStore,
    OAuthAccountError,
    OAuthAccountService,
    OAuthAccountStore,
    OAuthLinkProof,
    OAuthLoginOutcome,
    OAuthRevocationFailure,
    ProviderTokenReference,
    StoredProviderTokens,
    UnlinkOutcome,
    UnlinkStatus,
)
from litestar_security.providers.oauth._provider import (
    GitHubOAuthProvider,
    InvalidProviderGrantError,
    OAuthClientAuth,
    OAuthEndpointConfig,
    OAuthHTTPPolicy,
    OAuthProvider,
    OAuthProviderClient,
    OAuthProviderError,
    OAuthReauthenticationProvider,
    ProviderGrant,
    ProviderIdentity,
    ProviderTokenSet,
)
from litestar_security.providers.oauth._resource_server import (
    ProtectedResourceConfig,
    ProtectedResourceMetadata,
    build_protected_resource_handler,
)
from litestar_security.providers.oauth._routes import (
    OIDC_FRONTCHANNEL_LOGOUT,
    OAuthAuthorization,
    OAuthCallbackOutcome,
    OAuthConfig,
    OAuthConfirmation,
    OAuthLifecycle,
    OAuthLifecycleService,
    OAuthLink,
    OAuthLocalTransport,
    OAuthLogout,
    OAuthOperationSummary,
    OAuthProviderRegistration,
    OAuthReauthenticationOutcome,
    OAuthRevalidationOutcome,
    OAuthScopeUpgrade,
    OAuthStepUp,
    OAuthStepUpAuthorization,
    OAuthStepUpAuthorizer,
    OIDCBackchannelLogout,
    OIDCLogoutIdentity,
    OIDCLogoutLifecycleService,
    OIDCLogoutTokenConsumer,
    OIDCReauthenticationPolicy,
    OIDCSessionLogoutStore,
    StepUpOAuthAuthorizer,
    build_oauth_routes,
)
from litestar_security.providers.oauth._transactions import (
    OAUTH_BINDING_COOKIE_NAME,
    AESGCMOAuthTransactionProtector,
    InvalidOAuthCallback,
    MemoryOAuthTransactionStore,
    OAuthOperation,
    OAuthRedirectPolicy,
    OAuthTransaction,
    OAuthTransactionProtector,
    OAuthTransactionProtectorKey,
    OAuthTransactionService,
    OAuthTransactionStart,
    OAuthTransactionStore,
    OAuthTransactionUnavailable,
    ProtectedOAuthSecret,
    SecretStr,
    oauth_binding_cookie,
    pkce_s256,
)

if TYPE_CHECKING:
    from litestar_security.providers.oauth._local import OAuthLocalAuthTransport

__all__ = (
    "OAUTH_BINDING_COOKIE_NAME",
    "OIDC_FRONTCHANNEL_LOGOUT",
    "AESGCMOAuthTransactionProtector",
    "AccountLinkError",
    "GitHubOAuthProvider",
    "InvalidOAuthCallback",
    "InvalidProviderGrantError",
    "LinkedProviderAccount",
    "MemoryOAuthAccountStore",
    "MemoryOAuthTransactionStore",
    "OAuthAccountError",
    "OAuthAccountService",
    "OAuthAccountStore",
    "OAuthAuthorization",
    "OAuthCallbackOutcome",
    "OAuthClientAuth",
    "OAuthConfig",
    "OAuthConfirmation",
    "OAuthEndpointConfig",
    "OAuthHTTPPolicy",
    "OAuthLifecycle",
    "OAuthLifecycleService",
    "OAuthLink",
    "OAuthLinkProof",
    "OAuthLocalAuthTransport",
    "OAuthLocalTransport",
    "OAuthLoginOutcome",
    "OAuthLogout",
    "OAuthOperation",
    "OAuthOperationSummary",
    "OAuthProvider",
    "OAuthProviderClient",
    "OAuthProviderError",
    "OAuthProviderRegistration",
    "OAuthReauthenticationOutcome",
    "OAuthReauthenticationProvider",
    "OAuthRedirectPolicy",
    "OAuthRevalidationOutcome",
    "OAuthRevocationFailure",
    "OAuthScopeUpgrade",
    "OAuthStepUp",
    "OAuthStepUpAuthorization",
    "OAuthStepUpAuthorizer",
    "OAuthTransaction",
    "OAuthTransactionProtector",
    "OAuthTransactionProtectorKey",
    "OAuthTransactionService",
    "OAuthTransactionStart",
    "OAuthTransactionStore",
    "OAuthTransactionUnavailable",
    "OIDCBackchannelLogout",
    "OIDCLogoutIdentity",
    "OIDCLogoutLifecycleService",
    "OIDCLogoutTokenConsumer",
    "OIDCReauthenticationPolicy",
    "OIDCSessionLogoutStore",
    "ProtectedOAuthSecret",
    "ProtectedResourceConfig",
    "ProtectedResourceMetadata",
    "ProviderGrant",
    "ProviderIdentity",
    "ProviderTokenReference",
    "ProviderTokenSet",
    "SecretStr",
    "StepUpOAuthAuthorizer",
    "StoredProviderTokens",
    "UnlinkOutcome",
    "UnlinkStatus",
    "build_oauth_routes",
    "build_protected_resource_handler",
    "oauth_binding_cookie",
    "pkce_s256",
)


def __getattr__(name: str) -> Any:  # noqa: ANN401 - module lazy-export hooks are dynamically typed
    """Resolve the local-auth bridge without introducing provider cycles."""
    if name == "OAuthLocalAuthTransport":
        from litestar_security.providers.oauth._local import OAuthLocalAuthTransport  # noqa: PLC0415

        return OAuthLocalAuthTransport
    message = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(message)
