"""Curated authentication provider contracts."""

from importlib import import_module
from typing import TYPE_CHECKING, Any

from litestar_security._lazy import import_optional_attribute
from litestar_security.providers.api_key import (
    APIKeyClaims,
    APIKeyCodec,
    APIKeyConfig,
    APIKeyGenerationError,
    APIKeyProof,
    APIKeyService,
    APIKeyState,
    APIKeyStore,
    APIKeyUsageSink,
    BufferedAPIKeyUsage,
    IssuedAPIKey,
)
from litestar_security.providers.iap import GoogleIAPClaims, GoogleIAPConfig, GoogleIAPExternalIdentity
from litestar_security.providers.jwks import (
    AsyncJWKSFetcher,
    CachedJWKSProvider,
    HttpxJWKSFetcher,
    InMemoryJWKSCache,
    JWKSCache,
    JWKSCacheCoordinator,
    JWKSCachePolicy,
    JWKSFetchOutcome,
    JWKSFetchTarget,
    JWKSProvider,
    JWKSSnapshot,
    JWKSSource,
    NoOpSecurityMetrics,
    SecurityMetrics,
    SyncJWKSFetcher,
    WorkerLimits,
    normalize_fetcher,
)
from litestar_security.providers.jwt import (
    BearerSlotSelector,
    BearerTokenSlot,
    CompositeBearerConfig,
    JSONValue,
    JWTClaims,
    JWTValidationConfig,
    JWTVerifier,
    LocalJWKSConfig,
    LocalKeyRing,
    SigningKey,
    SyncJWTVerifier,
    SyncTokenSigner,
    TokenSigner,
    VerificationKey,
    VerificationKeySet,
    VerifiedCapability,
    build_access_token_claims,
    build_local_jwks_handler,
    extend_composite_bearer,
    normalize_signer,
    normalize_verifier,
)

if TYPE_CHECKING:
    from litestar_security.providers.oauth import (
        AESGCMOAuthTransactionProtector,
        GitHubOAuthProvider,
        OAuthAccountService,
        OAuthAccountStore,
        OAuthCallbackOutcome,
        OAuthConfig,
        OAuthConfirmation,
        OAuthLifecycle,
        OAuthLoginOutcome,
        OAuthProvider,
        OAuthReauthenticationOutcome,
        OAuthReauthenticationProvider,
        OAuthRevalidationOutcome,
        OAuthTransactionProtectorKey,
        OIDCReauthenticationPolicy,
        ProtectedResourceConfig,
    )
    from litestar_security.providers.oidc import (
        DiscoveryPolicy,
        KeycloakClaims,
        OIDCDiscoveryClient,
        OIDCDiscoveryError,
        OIDCJWTLogoutTokenConsumer,
        OIDCMetadata,
        OIDCProvider,
        ServiceTokenConfig,
        discover_google_oidc_provider,
        discover_oidc_provider,
        google_oidc_provider,
        keycloak_oidc_provider,
        map_keycloak_claims,
        oidc_provider,
    )

__all__ = (
    "AESGCMOAuthTransactionProtector",
    "APIKeyClaims",
    "APIKeyCodec",
    "APIKeyConfig",
    "APIKeyGenerationError",
    "APIKeyProof",
    "APIKeyService",
    "APIKeyState",
    "APIKeyStore",
    "APIKeyUsageSink",
    "AsyncJWKSFetcher",
    "BearerSlotSelector",
    "BearerTokenSlot",
    "BufferedAPIKeyUsage",
    "CachedJWKSProvider",
    "CompositeBearerConfig",
    "DiscoveryPolicy",
    "GitHubOAuthProvider",
    "GoogleIAPClaims",
    "GoogleIAPConfig",
    "GoogleIAPExternalIdentity",
    "HttpxJWKSFetcher",
    "InMemoryJWKSCache",
    "IssuedAPIKey",
    "JSONValue",
    "JWKSCache",
    "JWKSCacheCoordinator",
    "JWKSCachePolicy",
    "JWKSFetchOutcome",
    "JWKSFetchTarget",
    "JWKSProvider",
    "JWKSSnapshot",
    "JWKSSource",
    "JWTClaims",
    "JWTValidationConfig",
    "JWTVerifier",
    "KeycloakClaims",
    "LocalJWKSConfig",
    "LocalKeyRing",
    "NoOpSecurityMetrics",
    "OAuthAccountService",
    "OAuthAccountStore",
    "OAuthCallbackOutcome",
    "OAuthConfig",
    "OAuthConfirmation",
    "OAuthLifecycle",
    "OAuthLoginOutcome",
    "OAuthProvider",
    "OAuthReauthenticationOutcome",
    "OAuthReauthenticationProvider",
    "OAuthRevalidationOutcome",
    "OAuthTransactionProtectorKey",
    "OIDCDiscoveryClient",
    "OIDCDiscoveryError",
    "OIDCJWTLogoutTokenConsumer",
    "OIDCMetadata",
    "OIDCProvider",
    "OIDCReauthenticationPolicy",
    "ProtectedResourceConfig",
    "SecurityMetrics",
    "ServiceTokenConfig",
    "SigningKey",
    "SyncJWKSFetcher",
    "SyncJWTVerifier",
    "SyncTokenSigner",
    "TokenSigner",
    "VerificationKey",
    "VerificationKeySet",
    "VerifiedCapability",
    "WorkerLimits",
    "build_access_token_claims",
    "build_local_jwks_handler",
    "discover_google_oidc_provider",
    "discover_oidc_provider",
    "extend_composite_bearer",
    "google_oidc_provider",
    "keycloak_oidc_provider",
    "map_keycloak_claims",
    "normalize_fetcher",
    "normalize_signer",
    "normalize_verifier",
    "oidc_provider",
)

_OAUTH_EXPORTS = frozenset({
    "AESGCMOAuthTransactionProtector",
    "GitHubOAuthProvider",
    "OAuthAccountService",
    "OAuthAccountStore",
    "OAuthCallbackOutcome",
    "OAuthConfirmation",
    "OAuthConfig",
    "OAuthLoginOutcome",
    "OAuthProvider",
    "OAuthReauthenticationOutcome",
    "OAuthReauthenticationProvider",
    "OAuthRevalidationOutcome",
    "OAuthLifecycle",
    "OAuthTransactionProtectorKey",
    "OIDCReauthenticationPolicy",
    "ProtectedResourceConfig",
})
_OIDC_EXPORTS = frozenset({
    "DiscoveryPolicy",
    "KeycloakClaims",
    "OIDCDiscoveryClient",
    "OIDCDiscoveryError",
    "OIDCJWTLogoutTokenConsumer",
    "OIDCMetadata",
    "OIDCProvider",
    "ServiceTokenConfig",
    "discover_google_oidc_provider",
    "discover_oidc_provider",
    "google_oidc_provider",
    "keycloak_oidc_provider",
    "map_keycloak_claims",
    "oidc_provider",
})


def __getattr__(name: str) -> Any:  # noqa: ANN401 - module lazy-export hook is dynamically typed
    """Resolve OAuth exports without loading their provider tree eagerly."""
    if name in _OAUTH_EXPORTS:
        return import_optional_attribute(
            "litestar_security.providers.oauth", name, extras="oauth", dependencies=frozenset()
        )
    if name in _OIDC_EXPORTS:
        return getattr(import_module("litestar_security.providers.oidc"), name)
    message = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(message)
