"""Curated local-account, session, and refresh-token contracts."""

from importlib import import_module
from typing import TYPE_CHECKING, Any

from litestar_security._lazy import import_optional_attribute
from litestar_security.accounts._access_tokens import (
    LocalAccessToken,
    LocalAccessTokenIssuer,
    LocalBearerIdentityResolver,
)
from litestar_security.accounts._purpose_tokens import (
    NotificationCommand,
    PendingTokenIssue,
    PurposeTokenCodec,
    PurposeTokenDelivery,
    PurposeTokenGenerationError,
    PurposeTokenProof,
    RegistrationCommand,
    TokenIssue,
)
from litestar_security.accounts._rate_limits import (
    DEFAULT_RATE_LIMIT_POLICIES,
    RATE_LIMIT_STORE_NAME,
    RateLimitAttempt,
    RateLimitDecision,
    RateLimited,
    RateLimiter,
    RateLimitGuard,
    RateLimitPolicy,
    StoreRateLimiter,
    UnlimitedRateLimiter,
)
from litestar_security.accounts._receipts import (
    RefreshReceiptContext,
    RefreshReceiptKey,
    RefreshReceiptReplay,
    RefreshReceiptSealer,
)
from litestar_security.accounts._records import (
    ConsumeResult,
    ConsumeStatus,
    InvalidInvitation,
    LifecycleAccepted,
    LifecycleRejected,
    LocalAccountRecord,
    LocalAuthMode,
    LoginMethod,
    NoOpSecurityEventSink,
    PasswordChangeResult,
    PasswordChangeStatus,
    PasswordCredentialState,
    PasswordPolicyViolation,
    PasswordReauthenticationProof,
    PasswordResetResult,
    PasswordResetStatus,
    PasswordVerificationStatus,
    RegistrationMode,
    RegistrationResult,
    RegistrationStatus,
    RevokeLoginMethodResult,
    RevokeLoginMethodStatus,
    SecurityEvent,
    SecurityEventSink,
    TokenPurpose,
    normalize_identifier,
)
from litestar_security.accounts._refresh import (
    REFRESH_RESPONSE_HEADERS,
    CreateRefreshFamilyCommand,
    PrepareRefreshResult,
    RefreshTokenFamilyStore,
    RefreshTokenService,
    RotateRefreshCommand,
    RotateRefreshResult,
)
from litestar_security.accounts._refresh_tokens import (
    RefreshFamilyContext,
    RefreshRotationStatus,
    RefreshTokenCodec,
    RefreshTokenIssue,
    RefreshTokenProof,
    TokenPair,
)
from litestar_security.accounts._sessions import (
    CreateSessionCommand,
    NativeSessionAuth,
    NativeSessionStore,
    SessionAuthentication,
    SessionBindingConfig,
    SessionBindingProof,
    SessionRebindPlan,
    SessionRecord,
    SessionRegistry,
    SessionSummary,
)
from litestar_security.accounts._stores import (
    AccountLookup,
    LocalAccountCapabilities,
    LoginMethodStore,
    PasswordCredentialStore,
    RecoveryTokenStore,
    RegistrationPolicy,
    RegistrationStore,
    SecurityEpochStore,
    SecurityEpochValidator,
    VerificationTokenStore,
)
from litestar_security.accounts.schemas import (
    LocalAccount,
    LocalCredentials,
    LocalIdentifier,
    LocalInvitationRegistration,
    LocalMFAChallenge,
    LocalMFACompletion,
    LocalPasswordChange,
    LocalPasswordReset,
    LocalRegistration,
    LocalSession,
    LocalSessionList,
    LocalToken,
    PasskeyAuthenticationStart,
    PasskeyOptions,
    PasskeyRegistrationStart,
    PasskeySummary,
    PasskeyVerification,
    RecoveryCodes,
    RouteStatus,
    StepUpAuthorization,
    StepUpGrant,
    StepUpVerification,
    TOTPEnrollment,
    TOTPProvisioning,
    TOTPVerification,
)
from litestar_security.guards import AssuranceRequirement, AssuranceTrait

if TYPE_CHECKING:
    from litestar_security.accounts._auth_service import LocalAuthService, forwarded_client_key, trusted_client_key
    from litestar_security.accounts._login import PasswordLoginService, PasswordReauthenticationService
    from litestar_security.accounts._mfa import (
        AESGCMSecretProtector,
        MFAService,
        MFAStore,
        PendingTOTPEnrollment,
        ProtectedSecret,
        RecoveryCodeDigest,
        RecoveryCodeGrant,
        RecoveryCodePepper,
        SecretProtector,
        SecretProtectorKey,
        StepUpCredential,
        StepUpRecord,
        StepUpService,
        StepUpStore,
        TOTPMethod,
        TOTPPolicy,
        TOTPProvisioningGrant,
    )
    from litestar_security.accounts._mfa_login import MFALoginChallenge, MFALoginChallengeStore, MFARequired
    from litestar_security.accounts._passkeys import (
        AssertionRecordResult,
        AttestationTrustMapper,
        AuthenticationVerification,
        CloneRiskPolicy,
        InvalidWebAuthnResponseError,
        PasskeyCredential,
        PasskeyRecord,
        PasskeyService,
        PasskeyStore,
        PyWebAuthnVerifier,
        RegistrationVerification,
        UserVerification,
        WebAuthnChallenge,
        WebAuthnChallengeStore,
        WebAuthnOptions,
        WebAuthnVerifier,
    )
    from litestar_security.accounts._passwords import (
        Argon2PasswordHasher,
        PasswordHasher,
        PasswordHashingUnavailableError,
        PasswordPolicy,
        PasswordPolicyResult,
        PasswordVerificationResult,
    )
    from litestar_security.accounts._profiles import LocalAuth, LocalAuthConfig, LocalAuthSecrets
    from litestar_security.accounts._recovery import PasswordChangeService, RecoveryTokenService
    from litestar_security.accounts._registration import RegistrationService, VerificationTokenService
    from litestar_security.accounts.controllers import (
        LOCAL_AUTH_TAGS,
        build_local_auth_routes,
        build_mfa_routes,
        requires_local_bearer,
    )

__all__ = (
    "DEFAULT_RATE_LIMIT_POLICIES",
    "LOCAL_AUTH_TAGS",
    "RATE_LIMIT_STORE_NAME",
    "REFRESH_RESPONSE_HEADERS",
    "AESGCMSecretProtector",
    "AccountLookup",
    "Argon2PasswordHasher",
    "AssertionRecordResult",
    "AssuranceRequirement",
    "AssuranceTrait",
    "AttestationTrustMapper",
    "AuthenticationVerification",
    "CloneRiskPolicy",
    "ConsumeResult",
    "ConsumeStatus",
    "CreateRefreshFamilyCommand",
    "CreateSessionCommand",
    "InvalidInvitation",
    "InvalidWebAuthnResponseError",
    "LifecycleAccepted",
    "LifecycleRejected",
    "LocalAccessToken",
    "LocalAccessTokenIssuer",
    "LocalAccount",
    "LocalAccountCapabilities",
    "LocalAccountRecord",
    "LocalAuth",
    "LocalAuthConfig",
    "LocalAuthMode",
    "LocalAuthSecrets",
    "LocalAuthService",
    "LocalBearerIdentityResolver",
    "LocalCredentials",
    "LocalIdentifier",
    "LocalInvitationRegistration",
    "LocalMFAChallenge",
    "LocalMFACompletion",
    "LocalPasswordChange",
    "LocalPasswordReset",
    "LocalRegistration",
    "LocalSession",
    "LocalSessionList",
    "LocalToken",
    "LoginMethod",
    "LoginMethodStore",
    "MFALoginChallenge",
    "MFALoginChallengeStore",
    "MFARequired",
    "MFAService",
    "MFAStore",
    "NativeSessionAuth",
    "NativeSessionStore",
    "NoOpSecurityEventSink",
    "NotificationCommand",
    "PasskeyAuthenticationStart",
    "PasskeyCredential",
    "PasskeyOptions",
    "PasskeyRecord",
    "PasskeyRegistrationStart",
    "PasskeyService",
    "PasskeyStore",
    "PasskeySummary",
    "PasskeyVerification",
    "PasswordChangeResult",
    "PasswordChangeService",
    "PasswordChangeStatus",
    "PasswordCredentialState",
    "PasswordCredentialStore",
    "PasswordHasher",
    "PasswordHashingUnavailableError",
    "PasswordLoginService",
    "PasswordPolicy",
    "PasswordPolicyResult",
    "PasswordPolicyViolation",
    "PasswordReauthenticationProof",
    "PasswordReauthenticationService",
    "PasswordResetResult",
    "PasswordResetStatus",
    "PasswordVerificationResult",
    "PasswordVerificationStatus",
    "PendingTOTPEnrollment",
    "PendingTokenIssue",
    "PrepareRefreshResult",
    "ProtectedSecret",
    "PurposeTokenCodec",
    "PurposeTokenDelivery",
    "PurposeTokenGenerationError",
    "PurposeTokenProof",
    "PyWebAuthnVerifier",
    "RateLimitAttempt",
    "RateLimitDecision",
    "RateLimitGuard",
    "RateLimitPolicy",
    "RateLimited",
    "RateLimiter",
    "RecoveryCodeDigest",
    "RecoveryCodeGrant",
    "RecoveryCodePepper",
    "RecoveryCodes",
    "RecoveryTokenService",
    "RecoveryTokenStore",
    "RefreshFamilyContext",
    "RefreshReceiptContext",
    "RefreshReceiptKey",
    "RefreshReceiptReplay",
    "RefreshReceiptSealer",
    "RefreshRotationStatus",
    "RefreshTokenCodec",
    "RefreshTokenFamilyStore",
    "RefreshTokenIssue",
    "RefreshTokenProof",
    "RefreshTokenService",
    "RegistrationCommand",
    "RegistrationMode",
    "RegistrationPolicy",
    "RegistrationResult",
    "RegistrationService",
    "RegistrationStatus",
    "RegistrationStore",
    "RegistrationVerification",
    "RevokeLoginMethodResult",
    "RevokeLoginMethodStatus",
    "RotateRefreshCommand",
    "RotateRefreshResult",
    "RouteStatus",
    "SecretProtector",
    "SecretProtectorKey",
    "SecurityEpochStore",
    "SecurityEpochValidator",
    "SecurityEvent",
    "SecurityEventSink",
    "SessionAuthentication",
    "SessionBindingConfig",
    "SessionBindingProof",
    "SessionRebindPlan",
    "SessionRecord",
    "SessionRegistry",
    "SessionSummary",
    "StepUpAuthorization",
    "StepUpCredential",
    "StepUpGrant",
    "StepUpRecord",
    "StepUpService",
    "StepUpStore",
    "StepUpVerification",
    "StoreRateLimiter",
    "TOTPEnrollment",
    "TOTPMethod",
    "TOTPPolicy",
    "TOTPProvisioning",
    "TOTPProvisioningGrant",
    "TOTPVerification",
    "TokenIssue",
    "TokenPair",
    "TokenPurpose",
    "UnlimitedRateLimiter",
    "UserVerification",
    "VerificationTokenService",
    "VerificationTokenStore",
    "WebAuthnChallenge",
    "WebAuthnChallengeStore",
    "WebAuthnOptions",
    "WebAuthnVerifier",
    "build_local_auth_routes",
    "build_mfa_routes",
    "forwarded_client_key",
    "normalize_identifier",
    "requires_local_bearer",
    "trusted_client_key",
)

_MFA_EXPORTS = frozenset({
    "AESGCMSecretProtector",
    "MFAService",
    "MFAStore",
    "PendingTOTPEnrollment",
    "ProtectedSecret",
    "RecoveryCodeDigest",
    "RecoveryCodePepper",
    "RecoveryCodeGrant",
    "SecretProtector",
    "SecretProtectorKey",
    "StepUpCredential",
    "StepUpRecord",
    "StepUpService",
    "StepUpStore",
    "TOTPProvisioningGrant",
    "TOTPMethod",
    "TOTPPolicy",
})
_MFA_LOGIN_EXPORTS = frozenset({"MFALoginChallenge", "MFALoginChallengeStore", "MFARequired"})
_PASSKEY_EXPORTS = frozenset({
    "AssertionRecordResult",
    "AttestationTrustMapper",
    "AuthenticationVerification",
    "CloneRiskPolicy",
    "InvalidWebAuthnResponseError",
    "PasskeyCredential",
    "PasskeyService",
    "PasskeyStore",
    "PasskeyRecord",
    "PyWebAuthnVerifier",
    "RegistrationVerification",
    "UserVerification",
    "WebAuthnChallenge",
    "WebAuthnChallengeStore",
    "WebAuthnOptions",
    "WebAuthnVerifier",
})
_ARGON2_EXPORTS = frozenset({
    "Argon2PasswordHasher",
    "PasswordHasher",
    "PasswordHashingUnavailableError",
    "PasswordPolicy",
    "PasswordPolicyResult",
    "PasswordVerificationResult",
})
_LOGIN_EXPORTS = frozenset({"PasswordLoginService", "PasswordReauthenticationService"})
_REGISTRATION_EXPORTS = frozenset({"RegistrationService", "VerificationTokenService"})
_RECOVERY_EXPORTS = frozenset({"PasswordChangeService", "RecoveryTokenService"})
_AUTH_SERVICE_EXPORTS = frozenset({"LocalAuthService", "forwarded_client_key", "trusted_client_key"})
_PROFILE_EXPORTS = frozenset({"LocalAuth", "LocalAuthConfig", "LocalAuthSecrets"})
_CONTROLLER_EXPORTS = frozenset({
    "LOCAL_AUTH_TAGS",
    "build_local_auth_routes",
    "build_mfa_routes",
    "requires_local_bearer",
})
_OPTIONAL_EXPORTS = (
    dict.fromkeys(_MFA_EXPORTS, ("litestar_security.accounts._mfa", "mfa", frozenset({"pyotp"})))
    | dict.fromkeys(_MFA_LOGIN_EXPORTS, ("litestar_security.accounts._mfa_login", "mfa", frozenset({"pyotp"})))
    | dict.fromkeys(_PASSKEY_EXPORTS, ("litestar_security.accounts._passkeys", "passkeys", frozenset({"webauthn"})))
    | dict.fromkeys(_ARGON2_EXPORTS, ("litestar_security.accounts._passwords", "argon2", frozenset({"argon2"})))
    | dict.fromkeys(_LOGIN_EXPORTS, ("litestar_security.accounts._login", "argon2", frozenset({"argon2"})))
    | dict.fromkeys(
        _REGISTRATION_EXPORTS, ("litestar_security.accounts._registration", "argon2", frozenset({"argon2"}))
    )
    | dict.fromkeys(_RECOVERY_EXPORTS, ("litestar_security.accounts._recovery", "argon2", frozenset({"argon2"})))
    | dict.fromkeys(
        _AUTH_SERVICE_EXPORTS,
        ("litestar_security.accounts._auth_service", "argon2,mfa", frozenset({"argon2", "pyotp"})),
    )
    | dict.fromkeys(
        _PROFILE_EXPORTS, ("litestar_security.accounts._profiles", "argon2,mfa", frozenset({"argon2", "pyotp"}))
    )
)


def __getattr__(name: str) -> Any:  # noqa: ANN401 - module lazy-export hook is dynamically typed
    """Resolve optional local-account exports only when their features are installed."""
    if name in _CONTROLLER_EXPORTS:
        return getattr(import_module("litestar_security.accounts.controllers"), name)
    target = _OPTIONAL_EXPORTS.get(name)
    if target is not None:
        module_name, extras, dependencies = target
        return import_optional_attribute(module_name, name, extras=extras, dependencies=dependencies)
    message = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(message)
