"""Curated local-account, session, and refresh-token contracts."""

from importlib import import_module
from typing import TYPE_CHECKING, Any

from litestar_security._typing import import_optional_attribute
from litestar_security.accounts._rate_limits import (
    DEFAULT_RATE_LIMIT_POLICIES,
    RATE_LIMIT_STORE_NAME,
    RateLimitAttempt,
    RateLimitDecision,
    RateLimited,
    RateLimiter,
    RateLimitGuard,
    RateLimitPolicy,
    StoreRateLimiter,
    UnlimitedRateLimiter,
)
from litestar_security.accounts.models import (
    InvalidInvitation,
    LifecycleAccepted,
    LifecycleRejected,
    LocalAccountState,
    LocalAuthMode,
    LoginMethod,
    NoOpSecurityEventSink,
    PasswordChangeOutcome,
    PasswordChangeStatus,
    PasswordCredentialState,
    PasswordPolicyViolation,
    PasswordReauthenticationProof,
    PasswordResetOutcome,
    PasswordResetStatus,
    PasswordVerificationStatus,
    RegistrationMode,
    RegistrationOutcome,
    RegistrationStatus,
    RevokeLoginMethodOutcome,
    RevokeLoginMethodStatus,
    SecurityEvent,
    SecurityEventSink,
    TokenPurpose,
    VerificationOutcome,
    VerificationStatus,
    normalize_identifier,
)
from litestar_security.accounts.protocols import (
    AccountLookup,
    LocalAccountCapabilities,
    LoginMethodStore,
    PasswordCredentialStore,
    RateLimiterStore,
    RecoveryTokenStore,
    RefreshTokenFamilyStore,
    RegistrationPolicy,
    RegistrationStore,
    SecurityEpochStore,
    SecurityEpochValidator,
    SessionStore,
    VerificationTokenStore,
)
from litestar_security.accounts.schemas import (
    LocalAccount,
    LocalCredentials,
    LocalIdentifier,
    LocalInvitationRegistration,
    LocalMFAChallenge,
    LocalMFACompletion,
    LocalPasswordChange,
    LocalPasswordReset,
    LocalRegistration,
    LocalSession,
    LocalSessionList,
    LocalToken,
    OperationMessage,
    PasskeyAuthenticationStart,
    PasskeyOptions,
    PasskeyRegistrationStart,
    PasskeySummary,
    PasskeyVerification,
    RecoveryCodes,
    StepUpAuthorization,
    StepUpGrant,
    StepUpVerification,
    TOTPEnrollment,
    TOTPProvisioning,
    TOTPVerification,
)
from litestar_security.accounts.sessions import (
    CreateSessionCommand,
    NativeSessionAuth,
    NativeSessionStore,
    ResolvedUserAuthSession,
    SessionAuthentication,
    SessionBindingConfig,
    SessionBindingProof,
    SessionRebindPlan,
    SessionRegistry,
    SessionSummary,
    UserAuthSession,
    UserAuthSessionResolver,
)
from litestar_security.accounts.tokens import (
    REFRESH_RESPONSE_HEADERS,
    CreateRefreshFamilyCommand,
    LocalAccessToken,
    LocalAccessTokenIssuer,
    LocalBearerIdentityResolver,
    NotificationCommand,
    PendingTokenIssue,
    PurposeTokenCodec,
    PurposeTokenDelivery,
    PurposeTokenGenerationError,
    PurposeTokenProof,
    RefreshFamilyContext,
    RefreshPreflightOutcome,
    RefreshReceiptContext,
    RefreshReceiptKey,
    RefreshReceiptReplay,
    RefreshReceiptSealer,
    RefreshRotationOutcome,
    RefreshRotationStatus,
    RefreshTokenCodec,
    RefreshTokenIssue,
    RefreshTokenProof,
    RefreshTokenService,
    RegistrationCommand,
    RotateRefreshCommand,
    TokenIssue,
    TokenPair,
)
from litestar_security.guards import AssuranceRequirement, AssuranceTrait

if TYPE_CHECKING:
    from litestar_security.accounts._auth_service import LocalAuthService, forwarded_client_key, trusted_client_key
    from litestar_security.accounts._passkeys import (
        AttestationTrustMapper,
        AuthenticationVerification,
        CloneRiskPolicy,
        PasskeyAssertionStatus,
        PasskeyCredential,
        PasskeyMetadata,
        PasskeyService,
        PasskeyStore,
        PyWebAuthnVerifier,
        RegistrationVerification,
        UserVerification,
        WebAuthnChallenge,
        WebAuthnChallengeStore,
        WebAuthnOptions,
        WebAuthnVerificationError,
        WebAuthnVerifier,
    )
    from litestar_security.accounts._profiles import LocalAuth, LocalAuthConfig, LocalAuthSecrets
    from litestar_security.accounts.controllers import (
        LOCAL_AUTH_TAGS,
        build_local_auth_routes,
        build_mfa_routes,
        require_local_bearer,
    )
    from litestar_security.accounts.lifecycle import (
        PasswordChangeService,
        RecoveryTokenService,
        RegistrationService,
        VerificationTokenService,
    )
    from litestar_security.accounts.mfa import (
        AESGCMSecretProtector,
        MFALoginChallenge,
        MFALoginChallengeStore,
        MFARequired,
        MFAService,
        MFAStore,
        PendingTOTPEnrollment,
        ProtectedSecret,
        RecoveryCodeDigest,
        RecoveryCodeGrant,
        RecoveryCodePepper,
        SecretProtector,
        SecretProtectorKey,
        StepUpCredential,
        StepUpGrantState,
        StepUpService,
        StepUpStore,
        TOTPMethod,
        TOTPPolicy,
        TOTPProvisioningGrant,
        TOTPService,
        TOTPStore,
    )
    from litestar_security.accounts.passwords import (
        Argon2PasswordHasher,
        PasswordHasher,
        PasswordHashingUnavailableError,
        PasswordLoginService,
        PasswordPolicy,
        PasswordPolicyDecision,
        PasswordReauthenticationService,
        PasswordVerificationOutcome,
    )

__all__ = (
    "DEFAULT_RATE_LIMIT_POLICIES",
    "LOCAL_AUTH_TAGS",
    "RATE_LIMIT_STORE_NAME",
    "REFRESH_RESPONSE_HEADERS",
    "AESGCMSecretProtector",
    "AccountLookup",
    "Argon2PasswordHasher",
    "AssuranceRequirement",
    "AssuranceTrait",
    "AttestationTrustMapper",
    "AuthenticationVerification",
    "CloneRiskPolicy",
    "CreateRefreshFamilyCommand",
    "CreateSessionCommand",
    "InvalidInvitation",
    "LifecycleAccepted",
    "LifecycleRejected",
    "LocalAccessToken",
    "LocalAccessTokenIssuer",
    "LocalAccount",
    "LocalAccountCapabilities",
    "LocalAccountState",
    "LocalAuth",
    "LocalAuthConfig",
    "LocalAuthMode",
    "LocalAuthSecrets",
    "LocalAuthService",
    "LocalBearerIdentityResolver",
    "LocalCredentials",
    "LocalIdentifier",
    "LocalInvitationRegistration",
    "LocalMFAChallenge",
    "LocalMFACompletion",
    "LocalPasswordChange",
    "LocalPasswordReset",
    "LocalRegistration",
    "LocalSession",
    "LocalSessionList",
    "LocalToken",
    "LoginMethod",
    "LoginMethodStore",
    "MFALoginChallenge",
    "MFALoginChallengeStore",
    "MFARequired",
    "MFAService",
    "MFAStore",
    "NativeSessionAuth",
    "NativeSessionStore",
    "NoOpSecurityEventSink",
    "NotificationCommand",
    "OperationMessage",
    "PasskeyAssertionStatus",
    "PasskeyAuthenticationStart",
    "PasskeyCredential",
    "PasskeyMetadata",
    "PasskeyOptions",
    "PasskeyRegistrationStart",
    "PasskeyService",
    "PasskeyStore",
    "PasskeySummary",
    "PasskeyVerification",
    "PasswordChangeOutcome",
    "PasswordChangeService",
    "PasswordChangeStatus",
    "PasswordCredentialState",
    "PasswordCredentialStore",
    "PasswordHasher",
    "PasswordHashingUnavailableError",
    "PasswordLoginService",
    "PasswordPolicy",
    "PasswordPolicyDecision",
    "PasswordPolicyViolation",
    "PasswordReauthenticationProof",
    "PasswordReauthenticationService",
    "PasswordResetOutcome",
    "PasswordResetStatus",
    "PasswordVerificationOutcome",
    "PasswordVerificationStatus",
    "PendingTOTPEnrollment",
    "PendingTokenIssue",
    "ProtectedSecret",
    "PurposeTokenCodec",
    "PurposeTokenDelivery",
    "PurposeTokenGenerationError",
    "PurposeTokenProof",
    "PyWebAuthnVerifier",
    "RateLimitAttempt",
    "RateLimitDecision",
    "RateLimitGuard",
    "RateLimitPolicy",
    "RateLimited",
    "RateLimiter",
    "RateLimiterStore",
    "RecoveryCodeDigest",
    "RecoveryCodeGrant",
    "RecoveryCodePepper",
    "RecoveryCodes",
    "RecoveryTokenService",
    "RecoveryTokenStore",
    "RefreshFamilyContext",
    "RefreshPreflightOutcome",
    "RefreshReceiptContext",
    "RefreshReceiptKey",
    "RefreshReceiptReplay",
    "RefreshReceiptSealer",
    "RefreshRotationOutcome",
    "RefreshRotationStatus",
    "RefreshTokenCodec",
    "RefreshTokenFamilyStore",
    "RefreshTokenIssue",
    "RefreshTokenProof",
    "RefreshTokenService",
    "RegistrationCommand",
    "RegistrationMode",
    "RegistrationOutcome",
    "RegistrationPolicy",
    "RegistrationService",
    "RegistrationStatus",
    "RegistrationStore",
    "RegistrationVerification",
    "ResolvedUserAuthSession",
    "RevokeLoginMethodOutcome",
    "RevokeLoginMethodStatus",
    "RotateRefreshCommand",
    "SecretProtector",
    "SecretProtectorKey",
    "SecurityEpochStore",
    "SecurityEpochValidator",
    "SecurityEvent",
    "SecurityEventSink",
    "SessionAuthentication",
    "SessionBindingConfig",
    "SessionBindingProof",
    "SessionRebindPlan",
    "SessionRegistry",
    "SessionStore",
    "SessionSummary",
    "StepUpAuthorization",
    "StepUpCredential",
    "StepUpGrant",
    "StepUpGrantState",
    "StepUpService",
    "StepUpStore",
    "StepUpVerification",
    "StoreRateLimiter",
    "TOTPEnrollment",
    "TOTPMethod",
    "TOTPPolicy",
    "TOTPProvisioning",
    "TOTPProvisioningGrant",
    "TOTPService",
    "TOTPStore",
    "TOTPVerification",
    "TokenIssue",
    "TokenPair",
    "TokenPurpose",
    "UnlimitedRateLimiter",
    "UserAuthSession",
    "UserAuthSessionResolver",
    "UserVerification",
    "VerificationOutcome",
    "VerificationStatus",
    "VerificationTokenService",
    "VerificationTokenStore",
    "WebAuthnChallenge",
    "WebAuthnChallengeStore",
    "WebAuthnOptions",
    "WebAuthnVerificationError",
    "WebAuthnVerifier",
    "build_local_auth_routes",
    "build_mfa_routes",
    "forwarded_client_key",
    "normalize_identifier",
    "require_local_bearer",
    "trusted_client_key",
)

_MFA_EXPORTS = frozenset({
    "AESGCMSecretProtector",
    "MFAService",
    "MFAStore",
    "PendingTOTPEnrollment",
    "ProtectedSecret",
    "RecoveryCodeDigest",
    "RecoveryCodePepper",
    "RecoveryCodeGrant",
    "SecretProtector",
    "SecretProtectorKey",
    "StepUpCredential",
    "StepUpGrantState",
    "StepUpService",
    "StepUpStore",
    "TOTPMethod",
    "TOTPPolicy",
    "TOTPProvisioningGrant",
    "TOTPService",
    "TOTPStore",
})
_MFA_LOGIN_EXPORTS = frozenset({"MFALoginChallenge", "MFALoginChallengeStore", "MFARequired"})
_PASSKEY_EXPORTS = frozenset({
    "PasskeyAssertionStatus",
    "AttestationTrustMapper",
    "AuthenticationVerification",
    "CloneRiskPolicy",
    "WebAuthnVerificationError",
    "PasskeyCredential",
    "PasskeyService",
    "PasskeyStore",
    "PasskeyMetadata",
    "PyWebAuthnVerifier",
    "RegistrationVerification",
    "UserVerification",
    "WebAuthnChallenge",
    "WebAuthnChallengeStore",
    "WebAuthnOptions",
    "WebAuthnVerifier",
})
_ARGON2_EXPORTS = frozenset({
    "Argon2PasswordHasher",
    "PasswordHasher",
    "PasswordHashingUnavailableError",
    "PasswordPolicy",
    "PasswordPolicyDecision",
    "PasswordVerificationOutcome",
})
_LOGIN_EXPORTS = frozenset({"PasswordLoginService", "PasswordReauthenticationService"})
_REGISTRATION_EXPORTS = frozenset({"RegistrationService", "VerificationTokenService"})
_RECOVERY_EXPORTS = frozenset({"PasswordChangeService", "RecoveryTokenService"})
_AUTH_SERVICE_EXPORTS = frozenset({"LocalAuthService", "forwarded_client_key", "trusted_client_key"})
_PROFILE_EXPORTS = frozenset({"LocalAuth", "LocalAuthConfig", "LocalAuthSecrets"})
_CONTROLLER_EXPORTS = frozenset({
    "LOCAL_AUTH_TAGS",
    "build_local_auth_routes",
    "build_mfa_routes",
    "require_local_bearer",
})
_OPTIONAL_EXPORTS = (
    dict.fromkeys(_MFA_EXPORTS, ("litestar_security.accounts.mfa", "mfa", frozenset({"pyotp"})))
    | dict.fromkeys(_MFA_LOGIN_EXPORTS, ("litestar_security.accounts.mfa", "mfa", frozenset({"pyotp"})))
    | dict.fromkeys(_PASSKEY_EXPORTS, ("litestar_security.accounts._passkeys", "passkeys", frozenset({"webauthn"})))
    | dict.fromkeys(_ARGON2_EXPORTS, ("litestar_security.accounts.passwords", "argon2", frozenset({"argon2"})))
    | dict.fromkeys(_LOGIN_EXPORTS, ("litestar_security.accounts.passwords", "argon2", frozenset({"argon2"})))
    | dict.fromkeys(_REGISTRATION_EXPORTS, ("litestar_security.accounts.lifecycle", "argon2", frozenset({"argon2"})))
    | dict.fromkeys(_RECOVERY_EXPORTS, ("litestar_security.accounts.lifecycle", "argon2", frozenset({"argon2"})))
    | dict.fromkeys(
        _AUTH_SERVICE_EXPORTS,
        ("litestar_security.accounts._auth_service", "argon2,mfa", frozenset({"argon2", "pyotp"})),
    )
    | dict.fromkeys(
        _PROFILE_EXPORTS, ("litestar_security.accounts._profiles", "argon2,mfa", frozenset({"argon2", "pyotp"}))
    )
)


def __getattr__(name: str) -> Any:  # noqa: ANN401 - module lazy-export hook is dynamically typed
    """Resolve optional local-account exports only when their features are installed."""
    if name in _CONTROLLER_EXPORTS:
        return getattr(import_module("litestar_security.accounts.controllers"), name)
    target = _OPTIONAL_EXPORTS.get(name)
    if target is not None:
        module_name, extras, dependencies = target
        return import_optional_attribute(module_name, name, extras=extras, dependencies=dependencies)
    message = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(message)
